### ISSUE TITLE
Double-bracketed strings don't swallow the ultimate bracket

### ISSUE THREAD

**Issue by tigerw** [koesie10/LuaSerializer#3]
It appears that when parsing [[these strings]], a final square bracket is incorrectly left in the stream, leading to parse failures when further content/punctuation follows that bracket.

For example:

``` lua
{
    a = [[b]],
    c = "d"
}
```

demonstrates this.

I successfully implemented a local hotfix by adding the line `$this->input->next();` to https://github.com/koesie10/LuaSerializer/blob/a70f7db49b561b2969d33cc8d245541ba15989b3/src/TokenStream.php#L146

**Comment by tigerw** [comment]
In case you're wondering, I'm trying to parse [these files](https://github.com/cuberite/WorldEdit/blob/master/Info.lua) for [this repository](https://plugins.cuberite.org) for [Cuberite](https://cuberite.org) :P

**Comment by koesie10** [comment]
I've added that file to the tests and at least it doesn't give errors anymore, I haven't checked if the structure is completely correct.
