### ISSUE TITLE
Multilevel strings are not taken into account

### ISSUE THREAD

**Issue by tigerw** [koesie10/LuaSerializer#4]
Strings

``` lua
[=[ Like this ]=],
[=[ or [[ like this]] ]=]
```

aren't handled correctly. It just keeps getting better doesn't it :P

**Comment by koesie10** [comment]
How should those be handled? I can't easily find them in the Lua reference documentation for strings.

**Comment by tigerw** [comment]
I believe each = pair means on additional ]] in the comment is ignored to allow nesting of [[]]s.

Source: http://lua-users.org/wiki/StringsTutorial, nesting quotes.
