### ISSUE TITLE
Error on valid keyword `true` in lua

### ISSUE THREAD

**Issue by c33s** [koesie10/LuaSerializer#9]
```
In InputStream.php line 64:
  Unexpected keyword: true (125:20)
```
```
	["nested"] = {
		["foobar"] = {
			["common"] = true,
			["common_extra"] = true,
			["common_max_level"] = true,
			["common_extra_2"] = true,
		},
	},
```

**Comment by koesie10** [comment]
I cannot reproduce this issue with the following code:

```
$parser = new Parser(new TokenStream(new InputStream('{
    ["nested"] = {
		["foobar"] = {
			["common"] = true,
			["common_extra"] = true,
			["common_max_level"] = true,
			["common_extra_2"] = true,
		},
	},
}')));

$parser->parse();
```

Do you perhaps have a test case where it fails or would you be willing to share the complete file?

**Comment by c33s** [comment]
the same code you posted here fails on my system. 
this issue looks like a duplicate of https://github.com/koesie10/LuaSerializer/issues/8
so i assume you haven't tagged the latest release of your neat parser. i am using 0.3.0 

would you please create a new tag?

**Comment by koesie10** [comment]
I did indeed forget to tag a release, but v0.4 should now be available. Let me know whether it works for you.
